// user actions
export const USER_LOGIN = 'LOGIN';
export const USER_REGISTER = 'REGISTER';
export const USER_LOGOUT = 'LOGOUT';

// movie actions
export const FETCH_ACTIVE_MOVIE = 'FETCH_ACTIVE_MOVIE';
export const FETCH_MOST_POPULAR_MOVIES = 'FETCH_MOST_POPULAR_MOVIES';
export const FETCH_MOST_RATED_MOVIES = 'FETCH_MOST_RATED_MOVIES';
export const FETCH_TOP_MOVIES = 'FETCH_TOP_MOVIES';
export const FETCH_RECOMMENDED_MOVIES = 'FETCH_RECOMMENDED_MOVIES';
export const SEARCH_MOVIES = 'SEARCH_MOVIES';
export const GET_GENRES = 'GET_GENRES';

export const FETCH_USER_RATED_MOVIES = 'FETCH_USER_RATED_MOVIES';
export const FETCH_USER_SAVED_MOVIES = 'FETCH_USER_SAVED_MOVIES';
export const FETCH_USER_WATCHED_MOVIES = 'FETCH_USER_WATCHED_MOVIES';

export const FETCH_USER_MOVIE_STATUS = 'FETCH_USER_MOVIE_STATUS';
export const UPDATE_USER_MOVIE_STATUS = 'UPDATE_USER_MOVIE_STATUS';

// reviews
export const FETCH_REVIEWS_FOR_MOVIE = 'FETCH_REVIEWS_FOR_MOVIE';

// cinema actions
export const FETCH_CINEMAS_BY_CENTER_LOCATION = 'FETCH_CINEMAS_BY_CENTER_LOCATION';

// weather actions
export const FETCH_WEATHER_BY_LOCATION = 'FETCH_WEATHER_BY_LOCATION';

// app info actions
export const FETCH_APP_INFO = 'FETCH_APP_INFO';
